# Site wide configuration

title: Major Kong
description: "A beginners gets his FPV wings"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: http://www.majorkong.com

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Colin Blake
  web: http://www.majorkong.com
  email: colinblake@gmail.com
  #twitter: mmistakes
  bio: "An engineer learning to fly"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  #google:
  #  plus: +MichaelRoseDesign
  #  ad-client: ca-pub-7328585512091257
  #  ad-slot: 3049671934
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
